######################################################################
# Automatically generated by qmake (3.0) ? 1? 24 15:27:42 2017
######################################################################

TEMPLATE = app
TARGET = esp8266-vc-qt-gui
INCLUDEPATH += .

CONFIG += c++11

QT += core
QT += widgets
QT += network

# Input
HEADERS = window.h
SOURCES = main.cpp window.cpp
